/* =========================================================
   roster.js — 8 parodias de gente real.
   El chiste sale de quiénes son: sus poderes son sus memes.
   Nombres deformados a propósito: son caricaturas, no ellos.
   ========================================================= */

/* ---------- arte de proyectiles ---------- */
const ART = {
  bill: {
    pal: { g: '#3fa14a', G: '#7ede78', k: '#123a17', y: '#f5e07a' },
    rows: ['gggggggg', 'gGGGGGGg', 'gGykkyGg', 'gGykkyGg', 'gGGGGGGg', 'gggggggg']
  },
  cohete: {
    pal: { w: '#f2f2ef', r: '#e0343c', y: '#f5c542', d: '#8d97ad' },
    rows: ['..w..', '.rwr.', '.rwr.', '.rrr.', 'd.y.d', '.y.y.']
  },
  tuit: {
    pal: { w: '#f2f2ef', k: '#101726', c: '#48e0d0' },
    rows: ['wwwwww', 'wkwwkw', 'wwkkww', 'wkwwkw', 'wwwwww', 'cc....']
  },
  balon: {
    pal: { w: '#f2f2ef', k: '#1a1a1a' },
    rows: ['..www..', '.wkwkw.', 'wwwkwww', 'wkwwwkw', 'wwwkwww', '.wkwkw.', '..www..']
  },
  grito: {
    pal: { y: '#f5c542', w: '#fff2a8' },
    rows: ['..y..', '.y.w.', 'y.w.y', 'y.w.y', '.y.w.', '..y..']
  },
  plato: {
    pal: { w: '#f2f2ef', r: '#c0392b', p: '#f07a86' },
    rows: ['.wwwww.', 'wwprpww', 'wprrrpw', 'wwprpww', '.wwwww.']
  },
  sarten: {
    pal: { k: '#22252f', r: '#e0343c', y: '#f5c542' },
    rows: ['..rr...', '.ryyr..', 'kkkkkk.', 'kkkkkkk', '.kkkk..']
  },
  arbol: {
    pal: { G: '#4ad14a', D: '#2a7d3a', n: '#6b4a2a' },
    rows: ['..G..', '.GDG.', 'GGGGG', '.GDG.', '..n..', '..n..']
  },
  mancha: {
    pal: { p: '#f07ac0', b: '#9bb7f0' },
    rows: ['..pp..', '.pbbp.', 'pbbbbp', '.pbbp.', '..pp..', '.p..p.']
  },
  ceja: {
    pal: { k: '#3a2a1a', n: '#6b4a2a' },
    rows: ['...knn', '..kn..', '.kn...', 'kn....']
  },
  captcha: {
    pal: { k: '#101726', w: '#f2f2ef', c: '#48e0d0' },
    rows: ['kkkkkk', 'k.w.wk', 'kw.c.k', 'k.w.wk', 'kkkkkk']
  },
  onda: {
    pal: { p: '#f07ac0', l: '#ffc0e8', d: '#a03878' },
    rows: ['..d.l..', '.d.l.p.', 'd.l.p.p', 'd.l.p.p', 'd.l.p.p', '.d.l.p.', '..d.l..']
  },
  aullido: {
    pal: { l: '#ffc0e8', p: '#f07ac0', w: '#ffffff' },
    rows: ['..w..', '.wpw.', 'wplpw', 'wplpw', '.wpw.', '..w..']
  },
  formula: {
    pal: { w: '#ffffff', c: '#8ee0f0', k: '#1b3a4a' },
    rows: ['ccccccc', 'cwkwkwc', 'cwkwwwc', 'cwkwkwc', 'ccccccc']
  },
  grito2: {
    pal: { p: '#f050a0', l: '#ffb0d8', w: '#ffffff' },
    rows: ['..w..', '.wpw.', 'wplpw', 'wplpw', '.wpw.', '..w..']
  },
  doc: {
    pal: { w: '#f2f2ef', k: '#5a6478' },
    rows: ['wwwww', 'wkkkw', 'wwwww', 'wkkkw', 'wwwww']
  }
};

/* ---------- el elenco ---------- */
const ROSTER = [
  {
    id: 'trumpo', name: 'TRUMPO', short: 'TRUMPO', real: 'EL MAGNATE',
    title: 'CONSTRUCTOR DE MUROS', type: 'dinero', sub: 'LADRILLO',
    bio: 'PAGA EN EFECTIVO Y TE MANDA LA FACTURA.',
    voice: { f: 240, type: 'square', wob: 0.18, rate: 78 },
    speed: 1.05, power: 1.00, hp: 120, jump: 0.85, reach: 0.95, atkSpeed: 0.95,
    pal: { h: '#f0d97a', H: '#c9ae4e', l: '#fff0b8', s: '#f0a878', S: '#c07f52', L: '#ffc79a', e: '#c9a24e', m: '#a8404a', M: '#6b2028', W: '#ffffff', w: '#ffffff', k: '#1a1a1a' },
    head: ['........................',
           '.........hhhhhhhhh......',
           '......hhhhlllllllllh....',
           '....hhhhlllllllllhhhh...',
           '...hhhlllllllhhhhhhhh...',
           '...hhhhhhhhhhhhhhhhh....',
           '...hhhhhhsssssssshhh....',
           '...hhhhLLLLLLLLLLLhh....',
           '....sLLLLLLLLLLLLLLs....',
           '...sseeeeesssseeeeess...',
           '...sssseeesssseeessss...',
           '...sskkkksssssskkkkss...',
           '...sswkkwsssssswkkwss...',
           '...ssssssssssssssssss...',
           '...ssssssssSSssssssss...',
           '....ssssssSSSSssssss....',
           '....ssssssssssssssss....',
           '....ssssssMMMMssssss....',
           '.....ssssmmmmmmssss.....',
           '......ssssMMMMssss......',
           '.......SSSSSSSSSS.......',
           '.........SSSSSS.........',
           '.........SSSSSS.........',
           '.........SSSSSS.........'],
    body: { style: 'suit', main: '#26304a', dark: '#161c2c', light: '#f2f2ef', accent: '#c02a2a', skin: '#f0a878', legs: '#1e2638', legsDark: '#141a26' },
    special: { name: 'MURO DE ORO', cost: 30, kind: 'wall', dmg: 8, say: '¡Y LO PAGAS TÚ!' },
    superMove: { name: 'LLUVIA DE BILLETES', cost: 100, kind: 'projectile', dmg: 11, count: 6, spread: 0.9,
      speed: 2.1, gravity: 0.045, art: 'bill', oy: -60, life: 130, say: '¡EFECTIVO, MUCHO EFECTIVO!' },
    quotes: ['GANÉ. ENORME VICTORIA. LA MÁS GRANDE.', 'TE MANDÉ LA FACTURA DEL MURO.',
             'NADIE CONSTRUYE MUROS COMO YO. NADIE.'],
    barks: {
      intro: ['NADIE PELEA MEJOR QUE YO', 'ESTO VA A SER ENORME', 'GANO SIEMPRE, PREGUNTA'],
      hit: ['¡TREMENDO!', 'FANTÁSTICO, DE VERDAD', 'ESO FUE PERFECTO'],
      hurt: ['¡ESTO ES FRAUDE!', '¡ARBITRAJE AMAÑADO!', '¡LLAMEN A MIS ABOGADOS!'],
      block: ['MURO. GRAN MURO.', 'NO PASAS. NADIE PASA.'],
      gloat: ['TENGO EL MEJOR DINERO', 'LO COMPRÉ TODO YA'],
      low: ['NECESITO UN MURO MÁS ALTO', 'ESTO ES UNA CACERÍA DE BRUJAS'],
      win: ['GANÉ. ENORME VICTORIA.', 'LO DICE TODO EL MUNDO'],
      wall: ['¡ROMPISTE MI MURO!', '¡ESO LO PAGAS TÚ!', '¿QUIÉN TE DEJÓ ENTRAR?'],
      vs: { musko: 'TE COMPRO LA EMPRESA', zuck: 'VÉNDEME ESOS DATOS', bob: 'PÍNTAME EL MURO', shakira: 'TE COMPRO EL ESCENARIO', albertito: 'CÓRTATE ESE PELO', peluca: 'CON ESE PELO NO SE NEGOCIA', dibu: 'TE FICHO PARA MI CLUB' }
    },
    taunt: '¡TREMENDO!'
  },

  {
    id: 'musko', name: 'MUSKO', short: 'MUSKO', real: 'EL DE LOS COHETES',
    title: 'DIRECTOR DE TODO', type: 'cohete', sub: 'BETA PERMANENTE',
    bio: 'SUS COHETES A VECES SALEN AL REVÉS.',
    voice: { f: 330, type: 'triangle', wob: 0.30, rate: 58, slide: 40 },
    speed: 1.45, power: 1.15, hp: 85, jump: 1.15, reach: 1.0, atkSpeed: 1.10,
    pal: { h: '#4a3524', H: '#2e2016', l: '#6b4f34', s: '#f0c8a8', S: '#c49a78', L: '#ffe0c4', e: '#3a2a1c', m: '#a8555a', M: '#6b2a30', W: '#ffffff', w: '#ffffff', k: '#1a1a1a', b: '#5a4634' },
    head: ['........................',
           '........................',
           '........................',
           '....hhhhh......hhhhh....',
           '...hhhhhhhsssshhhhhhh...',
           '...hhhHHHHHHHHHHHHhhh...',
           '...hhhhhhhhhhhhhhhhhh...',
           '...hhhLLLLLLLLLLLLhhh...',
           '...hheeeeeLLLLLLLLLhh...',
           '...ssssssssssssssssss...',
           '...sskkkksssssekkkkss...',
           '...sswwkwsssssswwkwss...',
           '...sswkkwsssssswkkwss...',
           '...sssSSssssssssSSsss...',
           '...ssssssssSSssssssss...',
           '....ssssssSSSSssssss....',
           '....ssssssssssssssss....',
           '....bbbbbbbbbbmbbbbb....',
           '....bbbbsmmmmmmsbbbb....',
           '.....bbbbMbbbbbbbbb.....',
           '......bbbbbbbbbbbb......',
           '........bbbbbbbb........',
           '.........SSSSSS.........',
           '.........SSSSSS.........'],
    body: { style: 'jacket', main: '#22222c', dark: '#141419', light: '#3a3a4c', accent: '#e0343c', skin: '#f0c8a8', legs: '#39415e', legsDark: '#252b42' },
    special: { name: 'COHETE INESTABLE', cost: 30, kind: 'projectile', dmg: 16,
      speed: 3.1, gravity: 0.06, vy: -1.2, art: 'cohete', oy: -68, life: 150, splash: true,
      unstable: 0.3, say: 'ESTA VEZ SÍ ATERRIZA' },
    superMove: { name: 'HYPERLOOP', cost: 100, kind: 'teleport', dmg: 22,
      say: '¡TÚNEL TERMINADO!' },
    quotes: ['LO ARREGLO CON UNA ACTUALIZACIÓN DE SOFTWARE.', 'COMPRÉ EL RING. AHORA SE LLAMA X.',
             'TU DERROTA ESTABA EN LA HOJA DE RUTA.'],
    barks: {
      intro: ['ESTO SIGUE EN BETA', 'LO PROBAMOS EN VIVO', 'CONFÍA EN EL PROCESO'],
      hit: ['¡A LA LUNA!', 'ITERACIÓN EXITOSA', 'ESTO ESCALA BIEN'],
      hurt: ['ERA UNA PRUEBA', 'BUG CONOCIDO', 'LO PARCHEO LUEGO'],
      block: ['ESCUDO TÉRMICO', 'REDUNDANCIA ACTIVA'],
      gloat: ['ESTABA EN LA HOJA DE RUTA'],
      low: ['REINICIANDO SISTEMAS', 'NECESITO MÁS FONDOS'],
      win: ['LO COMPRÉ TODO Y GANÉ'],
      vs: { trumpo: 'TU MURO NO TIENE WIFI', zuck: 'TE RETO A UNA JAULA', albertito: 'ÉL NO INVENTÓ MI COHETE' }
    },
    taunt: '¡AL ESPACIO!'
  },

  {
    id: 'pulga', name: 'EL PULGA', short: 'PULGA', real: 'EL DE LA ZURDA',
    title: 'ZURDA REGISTRADA', type: 'futbol', sub: 'TRANQUILO',
    bio: 'CAMINA, CAMINA Y DE PRONTO TE ELIMINA.',
    voice: { f: 300, type: 'triangle', wob: 0.12, rate: 70 },
    speed: 1.60, power: 0.85, hp: 95, jump: 1.00, reach: 0.90, atkSpeed: 1.20,
    pal: { h: '#8a6a44', H: '#5f4830', l: '#a88a5c', s: '#e8b98f', S: '#bc8f66', L: '#ffd9b0', e: '#5f4830', m: '#8c4a4a', M: '#5a2a2a', W: '#ffffff', w: '#ffffff', k: '#1a1a1a', b: '#6b4f30', B: '#4a3520' },
    head: ['........................',
           '........................',
           '........hhhhhhhh........',
           '......hhHHHHHHhhhh......',
           '.....hhhhhhhhhhhhhh.....',
           '....hhhhhhhhhhhhhhhh....',
           '....hhhhhhhhhhhhhhhh....',
           '...hhhhLLLLLLLLLLhhhh...',
           '...hhhLLLLLLLLLLLLhhh...',
           '...hhssssessssesssshh...',
           '...sskkkksssssskkkkss...',
           '...sswwkwsssssswwkwss...',
           '...sswkkwsssssswkkwss...',
           '...sssSSssssssssSSsss...',
           '...ssssssssSSssssssss...',
           '...bbbssssSSSSssssbbb...',
           '...bbbbbbbbbbbbbbbbbb...',
           '...bbbbbBBBBBBBBbbbbb...',
           '...bbbbbsmmmmmmsbbbbb...',
           '....bbbbbbMbbMbbbbbb....',
           '.....bbbbbbbbbbbbbb.....',
           '.......bbbbbbbbbb.......',
           '.........SSSSSS.........',
           '.........SSSSSS.........'],
    body: { style: 'stripes', main: '#7fd0e8', dark: '#3a7f96', light: '#f2f2ef', accent: '#f5c542', skin: '#e8b98f', legs: '#e8ecf5', legsDark: '#b9c4d8' },
    special: { name: 'NARIZÓN', cost: 30, kind: 'poke', say: 'MIRÁ ESTO' },
    superMove: { name: 'GAMBETA INFINITA', cost: 100, kind: 'dash', dmg: 9, hits: 4, speed: 4.6, dur: 36,
      say: '¡SE FUE DE CUATRO!' },
    quotes: ['Y HOY TAMPOCO FUE PENAL.', 'LA PELOTA NO SE MANCHA. TU RÉCORD SÍ.',
             'ANDÁ, TRANQUILO, NO PASA NADA.'],
    barks: {
      intro: ['DALE, TRANQUILO', 'ANDÁ, VENÍ', 'JUGUEMOS Y YA'],
      hit: ['¡GOLAZO!', 'ANDÁ P’ALLÁ', 'AL ÁNGULO'],
      hurt: ['¡ESO ES FALTA!', '¡AMARILLA PARA ÉL!', 'ME PEGÓ, ÁRBITRO'],
      block: ['LA TOQUÉ, ÁRBITRO', 'NO PASA NADA'],
      gloat: ['ESTO NO SE ENSEÑA'],
      low: ['ME QUEDAN DOS MINUTOS', 'PIDO EL CAMBIO'],
      win: ['Y HOY TAMPOCO FUE PENAL'],
      vs: { siuuu: 'OTRA VEZ VOS NO', roca: 'NO ME EMPUJES ASÍ', dibu: 'DALE DIBU, ES BROMA' }
    },
    taunt: 'ANDÁ P’ALLÁ'
  },

  {
    id: 'siuuu', name: 'SIUUU', short: 'SIUUU', real: 'EL DEL SALTO',
    title: 'MÁQUINA DE SALTAR', type: 'ego', sub: 'ABDOMINALES',
    bio: 'SALTA MÁS ALTO QUE TU AUTOESTIMA.',
    voice: { f: 420, type: 'square', wob: 0.20, rate: 52, up: true },
    speed: 1.35, power: 1.05, hp: 100, jump: 1.35, reach: 1.05, atkSpeed: 1.00,
    pal: { h: '#211a14', H: '#0f0c08', l: '#3a2e22', s: '#e0a878', S: '#b07f54', L: '#ffc99a', e: '#0f0c08', m: '#8c3b3b', M: '#5a2020', W: '#ffffff', w: '#ffffff', k: '#2a1a1a' },
    head: ['........................',
           '........................',
           '.......hhhhhhhhhh.......',
           '.....hhhhhhhhhhhhhh.....',
           '....hhhHHHHHhhhhhhhh....',
           '...hhhHHHHHhhhhhhhhhh...',
           '...hhhhhhhhhhhhhhhhhh...',
           '...hhhLLLLLLLLLLLLhhh...',
           '...hheeeeeLLLLLLLLLhh...',
           '...ssssssssssssssssss...',
           '...sskkkksssssekkkkss...',
           '...sswwkwsssssswwkwss...',
           '...sswkkwsssssswkkwss...',
           '...sssSSssssssssSSsss...',
           '...ssssssssSSssssssss...',
           '....ssssssSSSSssssss....',
           '....ssssssssssssssss....',
           '....sssMMMMMMMMMMsss....',
           '.....sssWWWWWWWWsss.....',
           '......sssMMMMMMsss......',
           '.......SSSSSSSSSS.......',
           '.........SSSSSS.........',
           '.........SSSSSS.........',
           '.........SSSSSS.........'],
    body: { style: 'jersey', main: '#c0392b', dark: '#8f1218', light: '#f2f2ef', accent: '#f5c542', skin: '#e0a878', legs: '#f2f2ef', legsDark: '#c9cfdd' },
    special: { name: 'CABEZAZO ORBITAL', cost: 30, kind: 'dash', dmg: 11, hits: 2, speed: 4.4, dur: 30, air: true,
      say: '¡SIGO SUBIENDO!' },
    superMove: { name: 'GRITO SIUUU', cost: 100, kind: 'projectile', dmg: 13, count: 2, spread: 0.5,
      speed: 3.0, art: 'grito', oy: -60, life: 130, big: true, effect: 'slow', say: '¡SIUUUUUU!' },
    quotes: ['SOY EL MEJOR. LO DIGO YO, QUE SÉ DE ESTO.', 'ESAS CINCO LAS GANÉ SOLO.',
             'EL TALENTO SIN TRABAJO NO ES NADA. YO TENGO LOS DOS.'],
    barks: {
      intro: ['SIUUU', 'MÍRAME BIEN', 'SOY EL MEJOR, YA ESTÁ'],
      hit: ['¡SIUUU!', 'CALIDAD Y TRABAJO', 'ESO ES TÉCNICA'],
      hurt: ['¡ERA FALTA!', '¡ME EMPUJÓ!', 'ESO NO VALE'],
      block: ['ABDOMINALES DE ACERO', 'NI ME DESPEINO'],
      gloat: ['POR ESO SOY YO'],
      low: ['ESTO NO SE ACABA', 'AÚN SOY EL MEJOR'],
      win: ['LO HICE YO SOLO'],
      vs: { pulga: 'OTRA VEZ EL DE LA ZURDA', roca: 'YO TENGO MÁS ABDOMINALES', shakira: 'YO CANTO MEJOR' }
    },
    taunt: '¡SIUUU!'
  },

  {
    id: 'ramses', name: 'CHEF RAMSÉS', short: 'RAMSÉS', real: 'EL CHEF QUE GRITA',
    title: 'TODO ESTÁ CRUDO', type: 'cocina', sub: 'GRITO',
    bio: 'NUNCA VIO UN PLATO BIEN HECHO.',
    voice: { f: 200, type: 'sawtooth', wob: 0.35, rate: 44, growl: true },
    speed: 1.25, power: 1.10, hp: 105, jump: 0.95, reach: 1.00, atkSpeed: 1.05,
    pal: { h: '#e8d9a0', H: '#c0ad72', l: '#fff2c8', s: '#f2c9a0', S: '#c79c74', L: '#ffe4c6', e: '#c0ad72', m: '#a8555a', M: '#7a2a2a', W: '#ffffff', w: '#ffffff', k: '#1a1a1a' },
    head: ['....hh.hh.hh.hh.hh.hh...',
           '...hhhhhhhhhhhhhhhhhhh..',
           '....hhhhhhhhhhhhhhhh....',
           '...hhhlllllllhhhhhhhh...',
           '...hhhhhhhhhhhhhhhhhh...',
           '...hhhhhhhhhhhhhhhhhh...',
           '...hhhsssssssssssshhh...',
           '...hhsLLLLLLLLLLLLshh...',
           '....sLLLLLLLLLLLLLLs....',
           '...sseeeeesssseeeeess...',
           '...sskkkkessssekkkkss...',
           '...sswwkwsssssswwkwss...',
           '...sswkkwsssssswkkwss...',
           '...sssSSssssssssSSsss...',
           '...ssssssssSSssssssss...',
           '....ssssssSSSSssssss....',
           '....ssssssssssssssss....',
           '....ssssMMMMMMMMssss....',
           '.....ssMMmmmmmmMMss.....',
           '......ssMMMMMMMMss......',
           '.......SSSSSSSSSS.......',
           '.........SSSSSS.........',
           '.........SSSSSS.........',
           '.........SSSSSS.........'],
    body: { style: 'chef', main: '#f2f2ef', dark: '#c9cfdd', light: '#ffffff', accent: '#3a4560', skin: '#f2c9a0', legs: '#3a4560', legsDark: '#252b38' },
    special: { name: '¡ESTÁ CRUDO!', cost: 30, kind: 'projectile', dmg: 10, count: 2, spread: 0.35,
      speed: 3.2, art: 'plato', oy: -54, life: 120, say: '¡ESTO ESTÁ CRUDÍSIMO!' },
    superMove: { name: 'PESADILLA EN COCINA', cost: 100, kind: 'rain', dmg: 9, count: 7, art: 'sarten',
      effect: 'burn', say: '¡FUERA DE MI COCINA!' },
    quotes: ['¡ESTO ESTÁ MÁS CRUDO QUE TU DEFENSA!', 'TE DEJÉ QUEMADO POR FUERA Y TEMBLANDO POR DENTRO.',
             '¿ESTO LO HICISTE TÚ? ¿CON LAS MANOS?'],
    barks: {
      intro: ['¡ESTO ESTÁ CRUDO!', '¿QUÉ ES ESTO?', '¡SERVICIO EN CINCO!'],
      hit: ['¡FUERA DE MI COCINA!', '¡AL FUEGO!', '¡ASÍ SE HACE!'],
      hurt: ['¡ESTÁ FRÍO Y SOSO!', '¡SIN SAL Y SIN GRACIA!', '¡ESTO ES UN DESASTRE!'],
      block: ['SARTÉN ARRIBA', 'NO ENTRA NADA CRUDO'],
      gloat: ['POR FIN ALGO AL PUNTO'],
      low: ['SE ME QUEMA TODO', 'EL SERVICIO ES UN CAOS'],
      win: ['POR FIN ALGO BIEN HECHO'],
      vs: { bob: 'ESO NO SE COME', zuck: 'NINGUNA IA SABE SAZONAR', shakira: 'MENOS BAILE Y MÁS FUEGO' }
    },
    taunt: '¡ESTÁ CRUDO!'
  },

  {
    id: 'bob', name: 'BOB LA BROCHA', short: 'BOB', real: 'EL PINTOR AMABLE',
    title: 'ACCIDENTES FELICES', type: 'oleo', sub: 'ARBOLITO',
    bio: 'NO CREE EN LOS ERRORES. PEGA IGUAL.',
    voice: { f: 280, type: 'sine', wob: 0.10, rate: 96 },
    speed: 1.10, power: 0.90, hp: 115, jump: 0.90, reach: 1.00, atkSpeed: 0.90,
    pal: { h: '#6b4a2a', H: '#4a331c', l: '#8a6238', s: '#f2c9a0', S: '#c79c74', L: '#ffe4c6', e: '#4a331c', m: '#8c5b4b', M: '#5a3028', W: '#ffffff', w: '#ffffff', k: '#1a1a1a', b: '#5a3d22', B: '#3d2a16' },
    head: ['......hhhhhhhhhhhh......',
           '...hhhhhlhhhhhhhhhhhh...',
           '.hhhlhhhhhhhhhhhhlhhhhh.',
           'hhlhhhhhhhhhhhhhhhhhlhhh',
           'hhhhhhlhhhhhhhhhhhhhhhhh',
           'hhhhhhhhhhhhhhhlhhhhhhhh',
           'hhhhhsssssssssssssshhhhh',
           'hhhhssLLLLLLLLLLLLsshhhh',
           'hhh.sLLLLLLLLLLLLLLs.hhh',
           'hhhsseeeeesssseeeeesshhh',
           '...sskkkksssssskkkkss...',
           '...sswwkwsssssswwkwss...',
           '...sswkkwsssssswkkwss...',
           '...sssSSssssssssSSsss...',
           '...ssssssssSSssssssss...',
           '...bbbssssSSSSssssbbb...',
           '...bbbbbbbbbbbbbbbbbb...',
           '...bbbbbmBBBBBBmbbbbb...',
           '...bbbbbmmmmmmmmbbbbb...',
           '....bbbbbbbbbbbbbbbb....',
           '.....bbbbbbbbbbbbbb.....',
           '.......bbbbbbbbbb.......',
           '.........SSSSSS.........',
           '.........SSSSSS.........'],
    body: { style: 'shirt', main: '#7fa8d8', dark: '#4a6f9e', light: '#e8f0fa', accent: '#f0932b', skin: '#f2c9a0' },
    special: { name: 'ARBOLITO FELIZ', cost: 30, kind: 'heal', heal: 22, guard: 200, art: 'arbol', say: 'UN AMIGUITO AQUÍ' },
    superMove: { name: 'ACCIDENTE FELIZ', cost: 100, kind: 'rain', dmg: 8, count: 8, art: 'mancha',
      effect: 'slow', say: 'NO HAY ERRORES, SOLO ACCIDENTES FELICES' },
    quotes: ['NO PERDISTE, TUVISTE UN ACCIDENTE FELIZ.', 'UN ARBOLITO AQUÍ, UN MORETÓN ALLÁ.',
             'HOY PINTAMOS UNA NUBECITA. Y TU DERROTA.'],
    barks: {
      intro: ['HOY PINTAMOS ALGO BONITO', 'RESPIRA HONDO', 'SIN PRISA, AMIGO'],
      hit: ['ACCIDENTE FELIZ', 'UN TOQUECITO AQUÍ', 'QUEDA MUY BIEN'],
      hurt: ['NO PASA NADA', 'ESO TIENE ARREGLO', 'VAYA, QUÉ TEXTURA'],
      block: ['EL LIENZO AGUANTA', 'TRANQUILO, TRANQUILO'],
      gloat: ['MIRA QUÉ ARMONÍA'],
      low: ['NECESITO MÁS BLANCO', 'CASI ACABO EL CUADRO'],
      win: ['QUEDÓ PRECIOSO'],
      vs: { ramses: 'GRITAR NO PINTA NADA', trumpo: 'TE PINTO UNA PUERTA', peluca: 'PINTAR NO CUESTA NADA' }
    },
    taunt: 'TODO TIENE ARREGLO'
  },

  {
    id: 'roca', name: 'LA ROCA', short: 'LA ROCA', real: 'EL DE LA CEJA',
    title: '¿HUELES ESO?', type: 'roca', sub: 'CEJA',
    bio: 'DESAYUNA MÁS QUE TÚ EN UNA SEMANA.',
    voice: { f: 150, type: 'sawtooth', wob: 0.14, rate: 84, growl: true },
    speed: 0.95, power: 1.35, hp: 130, jump: 0.80, reach: 1.15, atkSpeed: 0.85,
    pal: { h: '#b0774a', H: '#8a5a34', l: '#c98f5e', s: '#b0774a', S: '#8a5a34', L: '#c98f5e', e: '#3a2418', m: '#7a3b3b', M: '#4a2020', W: '#ffffff', w: '#ffffff', k: '#1a1a1a' },
    head: ['........................',
           '........................',
           '........................',
           '........................',
           '........sLLLLLLs........',
           '......sLLLLLLLLLLs......',
           '.....ssssssssssssss.....',
           '....ssLLLLLLLLLLLLss....',
           '....seeeeeLLLLLLLLLs....',
           '...ssssssssssssssssss...',
           '...sskkkksssssekkkkss...',
           '...sswwkwsssssswwkwss...',
           '...sswkkwsssssswkkwss...',
           '...sssSSssssssssSSsss...',
           '...ssssssssSSssssssss...',
           '....ssssssSSSSssssss....',
           '....ssssssssssssssss....',
           '....ssssssssssmsssss....',
           '.....ssssmmmmmmssss.....',
           '......sssMssssssss......',
           '.......SSSSSSSSSS.......',
           '.........SSSSSS.........',
           '.........SSSSSS.........',
           '.........SSSSSS.........'],
    body: { style: 'tee', main: '#2e3240', dark: '#1b1e28', light: '#b0774a', accent: '#c9a06d', skin: '#b0774a', bulk: true, legs: '#5f5740', legsDark: '#413c2c' },
    special: { name: 'CEJA LEVANTADA', cost: 30, kind: 'projectile', dmg: 8,
      speed: 2.2, art: 'ceja', oy: -60, life: 120, effect: 'slow', say: '¿HUELES LO QUE ESTOY COCINANDO?' },
    superMove: { name: 'CODAZO DEL PUEBLO', cost: 100, kind: 'dash', dmg: 14, hits: 2, speed: 4.0, dur: 32,
      say: '¡ESTO VA POR EL PUEBLO!' },
    quotes: ['¿SABES LO QUE ESTABA COCINANDO? ESTO.', 'LEVANTÉ UNA CEJA Y TE CAÍSTE SOLO.',
             'NO ERES DEMASIADO PEQUEÑO. SOY YO, QUE SOY ENORME.'],
    barks: {
      intro: ['¿HUELES ESO?', 'MÍRAME A LA CEJA', 'VAMOS A TRABAJAR'],
      hit: ['¡ESTO VA POR EL PUEBLO!', '¿SABES QUÉ COCINABA?', '¡ARRIBA!'],
      hurt: ['ESO NI SE SIENTE', 'SIGUE INTENTÁNDOLO', 'ERA UN MASAJE'],
      block: ['PARED DE MÚSCULO', 'NI ME MUEVO'],
      gloat: ['DEMASIADO FÁCIL'],
      low: ['AHORA ME ENFADO', 'SE ACABÓ EL CALENTAMIENTO'],
      win: ['FIN DEL SERVICIO'],
      vs: { zuck: '¿ESO ES UN HUMANO?', pulga: 'NO TE ME ESCAPES', shakira: '¿ESO ES BAILE O QUÉ?' }
    },
    taunt: '¿HUELES ESO?'
  },

  {
    id: 'zuck', name: 'ZUCK-BOT', short: 'ZUCK', real: 'EL DE LA RED',
    title: 'HUMANO VERIFICADO', type: 'algoritmo', sub: 'CAPTCHA',
    bio: 'JURA QUE ES UNA PERSONA NORMAL.',
    voice: { f: 360, type: 'square', wob: 0.02, rate: 48 },
    speed: 1.20, power: 0.95, hp: 95, jump: 1.00, reach: 0.95, atkSpeed: 1.00,
    pal: { h: '#8a6a44', H: '#5f4830', l: '#a88a5c', s: '#f0e4dc', S: '#c9bdb4', L: '#fff6f0', e: '#5f4830', m: '#8c6b6b', M: '#5a4444', W: '#ffffff', w: '#ffffff', k: '#3a4560', c: '#48e0d0' },
    head: ['........................',
           '........................',
           '......hhhhhhhhhhhh......',
           '....hhhhhhhhhhhhhhhh....',
           '...hhhhhhhhhhhhhhhhhh...',
           '...hhhhhhhhhhhhhhhhhh...',
           '...hhhhhhhhhhhhhhhhhh...',
           '...hhHHHHHHHHHHHHHHhh...',
           '...hhhLLLLLLLLLLLLhhh...',
           '...hheeeeesssseeeeehh...',
           '...ssssssssssssssssss...',
           '...ssccccssssssccccss...',
           '...ssccwwssssssccwwss...',
           '...ssssssssssssssssss...',
           '...ssssssssSSssssssss...',
           '....ssssssSSSSssssss....',
           '....ssssssssssssssss....',
           '....ssssssssssssssss....',
           '.....ssskkkkkkkksss.....',
           '......ssssssssssss......',
           '.......SSSSSSSSSS.......',
           '.........SSSSSS.........',
           '.........SSSSSS.........',
           '.........SSSSSS.........'],
    body: { style: 'tee', main: '#6a7590', dark: '#414c66', light: '#f0e4dc', accent: '#48e0d0', skin: '#f0e4dc', legs: '#39415e', legsDark: '#252b42' },
    special: { name: '¿ERES UN ROBOT?', cost: 30, kind: 'projectile', dmg: 9, count: 2, spread: 0.3,
      speed: 3.4, art: 'captcha', oy: -54, life: 120, effect: 'slow', say: 'SELECCIONA TODOS LOS SEMÁFOROS' },
    superMove: { name: 'TÉRMINOS NUEVOS', cost: 100, kind: 'rain', dmg: 9, count: 8, art: 'doc',
      say: 'ACEPTAR O ACEPTAR' },
    quotes: ['HE ACEPTADO LOS TÉRMINOS DE TU DERROTA.', 'TU PARTIDA SE GUARDÓ. Y SE VENDIÓ.',
             'ESTO ES LO QUE UN HUMANO NORMAL DIRÍA AHORA.'],
    barks: {
      intro: ['HOLA. SOY HUMANO.', 'INICIANDO COMBATE', 'ME ALEGRA VERTE. ES CIERTO.'],
      hit: ['DATO REGISTRADO', 'ME GUSTA ESTO', 'INTERACCIÓN POSITIVA'],
      hurt: ['ERROR INESPERADO', 'REPORTANDO INCIDENCIA', 'ESO NO ESTABA EN EL PLAN'],
      block: ['FIREWALL ACTIVO', 'SOLICITUD DENEGADA'],
      gloat: ['EL ALGORITMO TE CONOCE'],
      low: ['MODO DE EMERGENCIA', 'GUARDANDO PARTIDA'],
      win: ['ACEPTASTE LOS TÉRMINOS'],
      vs: { roca: 'MÚSCULO NO ES UN DATO', trumpo: 'YA TENGO TUS DATOS', musko: 'COPIÉ TU FUNCIÓN', albertito: 'TU FÓRMULA ES OPEN SOURCE' }
    },
    taunt: 'ESTOY OPTIMIZANDO'
  },

  {
    id: 'shakira', name: 'LA LOBA', short: 'LOBA', real: 'LA DE LAS CADERAS',
    title: 'LAS CADERAS NO MIENTEN', type: 'ritmo', sub: 'ESCENARIO',
    bio: 'TE DESARMA BAILANDO Y ENCIMA TE LO CANTA.',
    voice: { f: 520, type: 'triangle', wob: 0.28, rate: 56, up: true },
    speed: 1.30, power: 1.00, hp: 100, jump: 1.10, reach: 0.95, atkSpeed: 1.10,
    pal: { h: '#e8c060', H: '#b8913a', l: '#ffe0a0', s: '#e8b585', S: '#c08f60', L: '#ffd7a8', e: '#8a6a30', m: '#c05070', M: '#7a2a44', W: '#ffffff', w: '#ffffff', k: '#1a1a1a', a: '#ffd166' },
    head: ['........................',
           '......hhhhhhhhhhhh......',
           '....hhhhllllllllhhhh....',
           '..hhhhlllllllhhhhhhhhh..',
           '.hhhhhhhhhhhhhhhhhhhhhh.',
           '.hhhhhhhhhhhhhhhhhhhhhh.',
           '.hhh.ssssssssssssss.hhh.',
           'hhhhssLLLLLLLLLLLLsshhhh',
           'hhh.sLLLLLLLLLLLLLLs.hhh',
           'hhhsseeeeesssseeeeesshhh',
           'hhhsskkkksssssskkkksshhh',
           'hhhsswwkwsssssswwkwsshhh',
           'hhhsswkkwsssssswkkwsshhh',
           'hhhsssSSssssssssSSssshhh',
           'hHHssssssssSSssssssssHHh',
           'hHHassssssSSSSssssss.HHh',
           'hHHassssssssssssssss.HHh',
           'hHH.ssssmssssssmssss.HHh',
           'hHH..sssmmmmmmmmsss..HHh',
           'hHH...ssssssssssss...HHh',
           '.HH....SSSSSSSSSS....HH.',
           '.........SSSSSS.........',
           '.........SSSSSS.........',
           '.........SSSSSS.........'],
    body: { style: 'stage', main: '#d8447a', dark: '#9c2a54', light: '#ffd166', accent: '#f0e0a0', skin: '#e8b585', legs: '#3a2a4a', legsDark: '#241a30' },
    special: { name: 'CADERAZO', cost: 30, kind: 'projectile', dmg: 12,
      speed: 1.7, art: 'onda', oy: -57, life: 46, push: 5, say: 'LAS CADERAS NO MIENTEN' },
    superMove: { name: 'AULLIDO', cost: 100, kind: 'projectile', dmg: 14, count: 2, spread: 0.45,
      speed: 2.6, art: 'aullido', oy: -74, life: 120, big: true, effect: 'stun', say: '¡AUUUUU!' },
    barks: {
      intro: ['¿BAILAMOS O PELEAMOS?', 'ESTO ES UN ESPECTÁCULO', 'SUERTE, LA VAS A NECESITAR'],
      hit: ['¡ESO SE SIENTE!', 'UN, DOS, TRES', 'AL RITMO, CARIÑO'],
      hurt: ['¡ME PISASTE!', 'ESO NO ESTABA ENSAYADO', 'FUERA DE COMPÁS'],
      block: ['NI ME DESPEINO', 'ESO NO ENTRA EN EL SHOW'],
      gloat: ['LAS CADERAS NUNCA MIENTEN'],
      low: ['ÚLTIMA CANCIÓN', 'ME QUEDA UN BIS'],
      win: ['GRACIAS, BUENAS NOCHES'],
      vs: { trumpo: 'TU MURO NO TIENE RITMO', albertito: 'ESTO NO SE CALCULA', siuuu: 'MENOS GRITO Y MÁS BAILE', dibu: 'ATAJAME ESTE PASO' }
    },
    quotes: ['LAS CADERAS NO MIENTEN. TÚ SÍ.', 'TE GANÉ Y ADEMÁS TE PUSE MÚSICA.',
             'GRACIAS, BUENAS NOCHES, HE SIDO YO.'],
    taunt: '¿ASÍ BAILAS?'
  },

  {
    id: 'albertito', name: 'ALBERTITO', short: 'ALBERT', real: 'EL DEL PELO',
    title: 'TODO ES RELATIVO', type: 'ciencia', sub: 'PIZARRA',
    bio: 'PEGA POCO PERO YA CALCULÓ DÓNDE VAS A ESTAR.',
    voice: { f: 260, type: 'sine', wob: 0.34, rate: 88 },
    speed: 1.00, power: 0.85, hp: 85, jump: 0.85, reach: 0.85, atkSpeed: 0.95,
    pal: { h: '#e8e8ee', H: '#b8b8c4', l: '#ffffff', s: '#f0d0b0', S: '#c9a883', L: '#fff0dc', e: '#c8c8d0', m: '#a8555a', M: '#6b2a30', W: '#ffffff', w: '#ffffff', k: '#1a1a1a', b: '#d8d8e0' },
    head: ['.hh.hh.hh.hh.hh.hh.hh.hh',
           '.hhhhlhhhhhhhhhhhhhhhhh.',
           'hhhhhhhhhhlhhhhhhhlhhhhh',
           'hhhlhhhhhhhhhhhhhhhhhlhh',
           'hhhhh...ssssssss...hhhhh',
           'hhhh..ssssssssssss..hhhh',
           'hhh..ssssssssssssss..hhh',
           'hhh.ssLLLLLLLLLLLLss.hhh',
           'hh..sLLLLLLLLLLLLLLs..hh',
           '...ssssssessssessssss...',
           '...sskkkksssssskkkkss...',
           '...sswwkwsssssswwkwss...',
           '...sswkkwsssssswkkwss...',
           '...sssSSssssssssSSsss...',
           '...ssssssssSSssssssss...',
           '....ssssssSSSSssssss....',
           '....sssbbbbbbbbbbsss....',
           '....ssbbMMMMMMMMbbss....',
           '.....ssMMmmmmmmMMss.....',
           '......ssMMMMMMMMss......',
           '.......SSSSSSSSSS.......',
           '.........SSSSSS.........',
           '.........SSSSSS.........',
           '.........SSSSSS.........'],
    body: { style: 'labcoat', main: '#e8e4dc', dark: '#b8b2a6', light: '#ffffff', accent: '#5a6478', skin: '#f0d0b0', legs: '#4a4740', legsDark: '#2e2c28', short: true },
    special: { name: 'E = M C 2', cost: 30, kind: 'projectile', dmg: 7,
      speed: 2.0, art: 'formula', oy: -60, life: 170, grow: true, say: 'ES SENCILLO, MIRA' },
    superMove: { name: 'AGUJERO NEGRO', cost: 100, kind: 'vortex', dmg: 4, say: 'ESTO SE VA A PONER DENSO' },
    barks: {
      intro: ['TODO ES RELATIVO', 'YA CALCULÉ ESTO', 'LA IMAGINACIÓN ES MÁS ÚTIL'],
      hit: ['LA FÓRMULA FUNCIONA', 'ERA PREVISIBLE', 'MASA POR VELOCIDAD'],
      hurt: ['DATO INESPERADO', 'HAY QUE REVISAR EL MODELO', 'ERROR EXPERIMENTAL'],
      block: ['CAMPO DE FUERZA', 'ESO YA LO PREVÍ'],
      gloat: ['LA CIENCIA GANA SIEMPRE'],
      low: ['NECESITO MÁS DATOS', 'REVISANDO HIPÓTESIS'],
      win: ['LO PUBLICARÉ MAÑANA'],
      vs: { musko: 'ESE COHETE ES MÍO', zuck: 'TU IA ME COPIÓ', roca: 'LA FÍSICA TIENE LÍMITES', peluca: 'RECORTAR CIENCIA SALE CARO' }
    },
    quotes: ['TODO ES RELATIVO. TU DERROTA NO.', 'LA LOCURA ES REPETIR ESTO ESPERANDO GANAR.',
             'NO ERA SUERTE, ERA GEOMETRÍA.'],
    taunt: 'FASCINANTE'
  },

  {
    id: 'peluca', name: 'EL PELUCA', short: 'PELUCA', real: 'EL DE LA MOTOSIERRA',
    title: 'AFUERA. TODO AFUERA.', type: 'motosierra', sub: 'AUSTERIDAD',
    bio: 'CORTA GASTO, PROYECTILES Y CONVERSACIONES.',
    voice: { f: 230, type: 'sawtooth', wob: 0.30, rate: 40, growl: true },
    speed: 1.35, power: 1.20, hp: 95, jump: 1.00, reach: 1.05, atkSpeed: 1.00,
    pal: { h: '#6b4a2a', H: '#4a331c', l: '#8a6238', s: '#e8b98f', S: '#bc8f66', L: '#ffd9b0', e: '#4a331c', m: '#8c3b3b', M: '#5a2020', W: '#ffffff', w: '#ffffff', k: '#1a1a1a', b: '#5a3d22' },
    head: ['.hh.hh.hh.hh.hh.hh.hh.hh',
           '.hhhhlhhhhhhhhhhhhhhhhh.',
           'hhhhhhhhhhlhhhhhhhlhhhhh',
           'hhhlhhhhhhhhhhhhhhhhhlhh',
           'hhhhh...ssssssss...hhhhh',
           'hhhh..ssssssssssss..hhhh',
           'hhh..ssssssssssssss..hhh',
           'hhh.ssLLLLLLLLLLLLss.hhh',
           'hh..sLLLLLLLLLLLLLLs..hh',
           '...sseeeeesssseeeeess...',
           '...sskkkkessssekkkkss...',
           '...sswwkwsssssswwkwss...',
           '...sswkkwsssssswkkwss...',
           '...sssSSssssssssSSsss...',
           '...ssssssssSSssssssss...',
           '....ssssssSSSSssssss....',
           '....ssssssssssssssss....',
           '....bbbbMMMMMMMMbbbb....',
           '....bbbMMmmmmmmMMbbb....',
           '.....bbbMMMMMMMMbbb.....',
           '......bbbbbbbbbbbb......',
           '........bbbbbbbb........',
           '.........SSSSSS.........',
           '.........SSSSSS.........'],
    body: { style: 'jacket', main: '#2a2a34', dark: '#16161c', light: '#3d3d4e', accent: '#7fd0e8', skin: '#e8b98f', legs: '#33334a', legsDark: '#20202e' },
    special: { name: '¡NO HAY PLATA!', cost: 30, kind: 'nullify', dmg: 6, drain: 40,
      say: '¡NO HAY PLATA!' },
    superMove: { name: 'MOTOSIERRA', cost: 100, kind: 'dash', dmg: 9, hits: 5, speed: 4.5, dur: 36,
      say: '¡AFUERA!' },
    barks: {
      intro: ['NO HAY PLATA', 'AFUERA. TODO AFUERA.', 'ESTO SE CORTA HOY'],
      hit: ['¡MOTOSIERRA!', '¡AFUERA!', 'AJUSTE APLICADO'],
      hurt: ['ESO NO ESTABA EN EL PLAN', 'ES HERENCIA RECIBIDA', 'DÉFICIT CERO, DIJE'],
      block: ['NO HAY PRESUPUESTO', 'ESO NO SE FINANCIA'],
      gloat: ['NO HAY PLATA, YA TE DIJE'],
      low: ['HAY QUE AGUANTAR', 'ES EL COSTO DEL AJUSTE'],
      win: ['NO HABÍA PLATA. AHORA TAMPOCO.'],
      vs: { trumpo: 'CON VOS NO HAY PLATA', musko: 'ESE COHETE ES GASTO PÚBLICO', bob: 'EL ARTE NO SE SUBVENCIONA', dibu: 'A VOS SÍ TE BANCO' }
    },
    quotes: ['NO HAY PLATA. NI PARA LA REVANCHA.', 'CORTÉ EL GASTO Y DE PASO TE CORTÉ A VOS.',
             'AFUERA. LITERALMENTE AFUERA.'],
    taunt: '¡AFUERA!'
  },

  {
    id: 'dibu', name: 'EL DIBU', short: 'DIBU', real: 'EL DE LOS PENALES',
    title: 'TE LO ATAJA Y TE LO CUENTA', type: 'arquero', sub: 'PSICOLOGÍA',
    bio: 'ATAJA TODO. INCLUSO LO QUE NO IBA AL ARCO.',
    voice: { f: 270, type: 'square', wob: 0.16, rate: 66 },
    speed: 1.15, power: 1.00, hp: 115, jump: 1.20, reach: 1.10, atkSpeed: 0.95,
    pal: { h: '#241a14', H: '#120d0a', l: '#3d2c20', s: '#dda87c', S: '#b07f54', L: '#ffc99a', e: '#120d0a', m: '#8c3b3b', M: '#5a2020', W: '#ffffff', w: '#ffffff', k: '#1a1a1a', b: '#241a14' },
    head: ['........................',
           '........................',
           '........hhhhhhhh........',
           '......hhHHHHHHhhhh......',
           '.....hhhhhhhhhhhhhh.....',
           '....hhhhhhhhhhhhhhhh....',
           '....hhhhhhhhhhhhhhhh....',
           '...hhhhLLLLLLLLLLhhhh...',
           '...hhhLLLLLLLLLLLLhhh...',
           '...hheeeeesssseeeeehh...',
           '...sssseeesssseeessss...',
           '...sskkkksssssskkkkss...',
           '...sswkkwsssssswkkwss...',
           '...ssssssssssssssssss...',
           '...ssssssssSSssssssss...',
           '....ssssssSSSSssssss....',
           '....ssssssssssssssss....',
           '....bbbbbbbbbbmbbbbb....',
           '....bbbbsmmmmmmsbbbb....',
           '.....bbbbMbbbbbbbbb.....',
           '......bbbbbbbbbbbb......',
           '........bbbbbbbb........',
           '.........SSSSSS.........',
           '.........SSSSSS.........'],
    body: { style: 'keeper', main: '#2f7f52', dark: '#1c4f33', light: '#c9f542', accent: '#ffffff', skin: '#dda87c', legs: '#1f2a24', legsDark: '#131a16', gloves: '#c9f542' },
    special: { name: 'ATAJADA', cost: 30, kind: 'catch', frames: 100, say: 'VENÍ, VENÍ' },
    superMove: { name: 'TE LO ATAJO', cost: 100, kind: 'psych', dmg: 8, steal: 100, say: 'MIRÁ QUE TE LO ATAJO' },
    barks: {
      intro: ['MIRÁ QUE TE LO ATAJO', 'PATEÁ TRANQUILO', 'YA SÉ PARA DÓNDE VAS'],
      hit: ['¡VAMOS!', 'TE LO DIJE', 'ACÁ NO ENTRA NADA'],
      hurt: ['ESA NO LA VI', 'ME DISTRAJERON', 'FUE CONTRA'],
      block: ['ATAJADA', 'ACÁ NO PASA'],
      gloat: ['SIEMPRE ADIVINO EL PALO'],
      low: ['AGUANTO HASTA LOS PENALES', 'ESTO SE DEFINE EN PENALES'],
      win: ['TE LO ATAJÉ TODO'],
      vs: { pulga: 'DALE LEO, TRANQUILO', siuuu: 'MIRÁ QUE TE LO ATAJO', ramses: 'ESE PLATO ES MÍO', peluca: 'A VOS TE BANCO IGUAL' }
    },
    quotes: ['TE LO ATAJÉ Y ENCIMA TE LO CUENTO.', 'ESTO SE DEFINÍA EN PENALES. SIEMPRE.',
             'MIRÁ QUE TE LO ATAJO. TE LO DIJE.'],
    taunt: 'ACÁ NO ENTRA'
  },

  {
    id: 'cresta', name: 'LA CRESTA', short: 'CRESTA', real: 'LA DE LA PANCARTA',
    title: 'SE ESCUCHA DESDE LA PLAZA', type: 'megafono', sub: 'ASAMBLEA',
    bio: 'TRAE MEGÁFONO, PANCARTA Y CERO GANAS DE DEBATIR AHORA.',
    voice: { f: 400, type: 'square', wob: 0.24, rate: 46, up: true },
    speed: 1.25, power: 1.05, hp: 100, jump: 1.05, reach: 1.20, atkSpeed: 0.95,
    pal: { h: '#f050a0', H: '#3a2a3a', l: '#ffb0d8', s: '#e8b98f', S: '#bc8f66', L: '#ffd9b0', e: '#3a2a3a', m: '#a8404a', M: '#6b2028', W: '#ffffff', w: '#ffffff', k: '#1a1a1a', a: '#ffd166' },
    head: ['.........h.h.h..........',
           '.........hlhhhh.........',
           '.........Hlhhhh.........',
           '.........hhlhhH.........',
           '....HHHHhhlhhhhhHHHH....',
           '...HHHHHhhhhlhhhHHHHH...',
           '...HHHHHhhhhhhhhHHHHH...',
           '...HHHLLLLLLLLLLLLHHH...',
           '...HHLLLLLLLLLLLLLLHH...',
           '...sseeeeesssseeeeess...',
           '...sskkkkessssekkkkss...',
           '...sswwkwsssssswwkwss...',
           '...sswkkwsssssswkkwss...',
           '...sssSSssssssssSSsss...',
           '...ssssssssSSssssssss...',
           '....sssssaSSSSssssss....',
           '....sssssassssssssss....',
           '....ssssMMMMMMMMssss....',
           '.....ssMMmmmmmmMMss.....',
           '......ssMMMMMMMMss......',
           '.......SSSSSSSSSS.......',
           '.........SSSSSS.........',
           '.........SSSSSS.........',
           '.........SSSSSS.........'],
    body: { style: 'punk', main: '#2e2836', dark: '#1a1620', light: '#f050a0', accent: '#ffd166', skin: '#e8b98f', legs: '#3d3348', legsDark: '#241d2c' },
    special: { name: 'MEGAFONAZO', cost: 30, kind: 'cone', dmg: 13, push: 7.5, say: '¡SE VA A OÍR!' },
    superMove: { name: 'MANIFESTACIÓN', cost: 100, kind: 'march', dmg: 7, count: 6, say: '¡NO VENGO SOLA!' },
    barks: {
      intro: ['ESTO SE DEBATE FUERA', 'TENGO FIRMAS PARA ESTO', 'VENGO CON MEGÁFONO'],
      hit: ['¡SE VA A OÍR!', 'ESO POR NO ESCUCHAR', '¡ORDEN EN LA SALA!'],
      hurt: ['NO ME LEVANTES LA VOZ', 'ESO LO DENUNCIO', 'SIGO AQUÍ, ¿EH?'],
      block: ['LA PANCARTA AGUANTA', 'ESO NO ME CALLA'],
      gloat: ['TE LO DIJE POR MEGÁFONO'],
      low: ['NO ME PIENSO CALLAR', 'QUEDA ASAMBLEA'],
      win: ['ACTA APROBADA POR UNANIMIDAD'],
      vs: { trumpo: 'CONTIGO TENGO PANCARTAS DE SOBRA', siuuu: 'MENOS EGO Y MÁS ESCUCHAR',
            zuck: 'BÓRRAME LOS DATOS', roca: 'EL TAMAÑO NO ES UN ARGUMENTO',
            peluca: 'ESTO NO SE RECORTA', ramses: 'A MÍ NO ME GRITAS' }
    },
    quotes: ['ACTA APROBADA. TE GANÉ POR UNANIMIDAD.', 'TE LO AVISÉ POR MEGÁFONO Y NO ESCUCHASTE.',
             'LA PRÓXIMA TRAIGO A TODA LA PLAZA.'],
    taunt: '¡MÁS ALTO!'
  }
];

const byId = id => ROSTER.find(c => c.id === id);
