/* =========================================================
   roster.js — 8 parodias de gente real.
   El chiste sale de quiénes son: sus poderes son sus memes.
   Nombres deformados a propósito: son caricaturas, no ellos.
   ========================================================= */

/* ---------- arte de proyectiles ---------- */
const ART = {
  bill: {
    pal: { g: '#3fa14a', G: '#7ede78', k: '#123a17', y: '#f5e07a' },
    rows: ['gggggggg', 'gGGGGGGg', 'gGykkyGg', 'gGykkyGg', 'gGGGGGGg', 'gggggggg']
  },
  cohete: {
    pal: { w: '#f2f2ef', r: '#e0343c', y: '#f5c542', d: '#8d97ad' },
    rows: ['..w..', '.rwr.', '.rwr.', '.rrr.', 'd.y.d', '.y.y.']
  },
  tuit: {
    pal: { w: '#f2f2ef', k: '#101726', c: '#48e0d0' },
    rows: ['wwwwww', 'wkwwkw', 'wwkkww', 'wkwwkw', 'wwwwww', 'cc....']
  },
  balon: {
    pal: { w: '#f2f2ef', k: '#1a1a1a' },
    rows: ['..www..', '.wkwkw.', 'wwwkwww', 'wkwwwkw', 'wwwkwww', '.wkwkw.', '..www..']
  },
  grito: {
    pal: { y: '#f5c542', w: '#fff2a8' },
    rows: ['..y..', '.y.w.', 'y.w.y', 'y.w.y', '.y.w.', '..y..']
  },
  plato: {
    pal: { w: '#f2f2ef', r: '#c0392b', p: '#f07a86' },
    rows: ['.wwwww.', 'wwprpww', 'wprrrpw', 'wwprpww', '.wwwww.']
  },
  sarten: {
    pal: { k: '#22252f', r: '#e0343c', y: '#f5c542' },
    rows: ['..rr...', '.ryyr..', 'kkkkkk.', 'kkkkkkk', '.kkkk..']
  },
  arbol: {
    pal: { G: '#4ad14a', D: '#2a7d3a', n: '#6b4a2a' },
    rows: ['..G..', '.GDG.', 'GGGGG', '.GDG.', '..n..', '..n..']
  },
  mancha: {
    pal: { p: '#f07ac0', b: '#9bb7f0' },
    rows: ['..pp..', '.pbbp.', 'pbbbbp', '.pbbp.', '..pp..', '.p..p.']
  },
  ceja: {
    pal: { k: '#3a2a1a', n: '#6b4a2a' },
    rows: ['...knn', '..kn..', '.kn...', 'kn....']
  },
  captcha: {
    pal: { k: '#101726', w: '#f2f2ef', c: '#48e0d0' },
    rows: ['kkkkkk', 'k.w.wk', 'kw.c.k', 'k.w.wk', 'kkkkkk']
  },
  onda: {
    pal: { p: '#f07ac0', l: '#ffc0e8', d: '#a03878' },
    rows: ['..d.l..', '.d.l.p.', 'd.l.p.p', 'd.l.p.p', 'd.l.p.p', '.d.l.p.', '..d.l..']
  },
  aullido: {
    pal: { l: '#ffc0e8', p: '#f07ac0', w: '#ffffff' },
    rows: ['..w..', '.wpw.', 'wplpw', 'wplpw', '.wpw.', '..w..']
  },
  formula: {
    pal: { w: '#ffffff', c: '#8ee0f0', k: '#1b3a4a' },
    rows: ['ccccccc', 'cwkwkwc', 'cwkwwwc', 'cwkwkwc', 'ccccccc']
  },
  doc: {
    pal: { w: '#f2f2ef', k: '#5a6478' },
    rows: ['wwwww', 'wkkkw', 'wwwww', 'wkkkw', 'wwwww']
  }
};

/* ---------- el elenco ---------- */
const ROSTER = [
  {
    id: 'trumpo', name: 'TRUMPO', short: 'TRUMPO', real: 'EL MAGNATE',
    title: 'CONSTRUCTOR DE MUROS', type: 'dinero', sub: 'LADRILLO',
    bio: 'PAGA EN EFECTIVO Y TE MANDA LA FACTURA.',
    speed: 1.05, power: 1.00, hp: 120, jump: 0.85, reach: 0.95, atkSpeed: 0.95,
    pal: { h: '#f0d97a', H: '#c9ae4e', s: '#f0a878', S: '#c07f52', L: '#ffc79a', w: '#ffffff', k: '#1a1a1a', e: '#c9a24e', m: '#a8404a' },
    head: ['................',
           '.....hhhhhh.....',
           '...hhhhhhhhhh...',
           '..hhHHHHhhhhhh..',
           '..hHHHHHHhhhhh..',
           '.hhssssssssshhh.',
           '.hsssssssssssss.',
           '.sseeesseeessss.',
           '.sswkwsswkwssss.',
           '.ssssssssssssss.',
           '.sssssSSssssss..',
           '.ssssSSSSsssss..',
           '.sssmmmmmsssss..',
           '.SsssssssssssS..',
           '..SSSSSSSSSSS...',
           '....ssssss......'],
    body: { style: 'suit', main: '#26304a', dark: '#161c2c', light: '#f2f2ef', accent: '#c02a2a', skin: '#f0a878', legs: '#1e2638', legsDark: '#141a26' },
    special: { name: 'MURO DE ORO', cost: 30, kind: 'wall', dmg: 8, say: '¡Y LO PAGAS TÚ!' },
    superMove: { name: 'LLUVIA DE BILLETES', cost: 100, kind: 'projectile', dmg: 11, count: 6, spread: 0.9,
      speed: 2.1, gravity: 0.045, art: 'bill', oy: -49, life: 130, say: '¡EFECTIVO, MUCHO EFECTIVO!' },
    quotes: ['GANÉ. ENORME VICTORIA. LA MÁS GRANDE.', 'TE MANDÉ LA FACTURA DEL MURO.',
             'NADIE CONSTRUYE MUROS COMO YO. NADIE.'],
    barks: {
      intro: ['NADIE PELEA MEJOR QUE YO', 'ESTO VA A SER ENORME', 'GANO SIEMPRE, PREGUNTA'],
      hit: ['¡TREMENDO!', 'FANTÁSTICO, DE VERDAD', 'ESO FUE PERFECTO'],
      hurt: ['¡ESTO ES FRAUDE!', '¡ARBITRAJE AMAÑADO!', '¡LLAMEN A MIS ABOGADOS!'],
      block: ['MURO. GRAN MURO.', 'NO PASAS. NADIE PASA.'],
      gloat: ['TENGO EL MEJOR DINERO', 'LO COMPRÉ TODO YA'],
      low: ['NECESITO UN MURO MÁS ALTO', 'ESTO ES UNA CACERÍA DE BRUJAS'],
      win: ['GANÉ. ENORME VICTORIA.', 'LO DICE TODO EL MUNDO'],
      wall: ['¡ROMPISTE MI MURO!', '¡ESO LO PAGAS TÚ!', '¿QUIÉN TE DEJÓ ENTRAR?'],
      vs: { musko: 'TE COMPRO LA EMPRESA', zuck: 'VÉNDEME ESOS DATOS', bob: 'PÍNTAME EL MURO', shakira: 'TE COMPRO EL ESCENARIO', albertito: 'CÓRTATE ESE PELO' }
    },
    taunt: '¡TREMENDO!'
  },

  {
    id: 'musko', name: 'MUSKO', short: 'MUSKO', real: 'EL DE LOS COHETES',
    title: 'DIRECTOR DE TODO', type: 'cohete', sub: 'BETA PERMANENTE',
    bio: 'SUS COHETES A VECES SALEN AL REVÉS.',
    speed: 1.45, power: 1.15, hp: 85, jump: 1.15, reach: 1.0, atkSpeed: 1.10,
    pal: { h: '#4a3524', H: '#2e2016', s: '#f0c8a8', S: '#c49a78', L: '#ffe0c4', w: '#ffffff', k: '#1a1a1a', e: '#3a2a1c', m: '#a8555a' },
    head: ['................',
           '....hhhhhhhh....',
           '..hhhhhhhhhhhh..',
           '.hhhhhhhhhhhhhh.',
           '.hHssssssssssHh.',
           '.hsssssssssssss.',
           '.sseeesseeessss.',
           '.sswkwsswkwssss.',
           '.ssssssssssssss.',
           '.ssssssSSssssss.',
           '.sssssSSSSsssss.',
           '.ssssmmmmmmssss.',
           '.ssssssssssssss.',
           '.SsssssssssssS..',
           '..SSSSSSSSSSS...',
           '....ssssss......'],
    body: { style: 'jacket', main: '#22222c', dark: '#141419', light: '#3a3a4c', accent: '#e0343c', skin: '#f0c8a8', legs: '#39415e', legsDark: '#252b42' },
    special: { name: 'COHETE INESTABLE', cost: 30, kind: 'projectile', dmg: 16,
      speed: 3.1, gravity: 0.06, vy: -1.2, art: 'cohete', oy: -55, life: 150, splash: true,
      unstable: 0.3, say: 'ESTA VEZ SÍ ATERRIZA' },
    superMove: { name: 'HYPERLOOP', cost: 100, kind: 'teleport', dmg: 22,
      say: '¡TÚNEL TERMINADO!' },
    quotes: ['LO ARREGLO CON UNA ACTUALIZACIÓN DE SOFTWARE.', 'COMPRÉ EL RING. AHORA SE LLAMA X.',
             'TU DERROTA ESTABA EN LA HOJA DE RUTA.'],
    barks: {
      intro: ['ESTO SIGUE EN BETA', 'LO PROBAMOS EN VIVO', 'CONFÍA EN EL PROCESO'],
      hit: ['¡A LA LUNA!', 'ITERACIÓN EXITOSA', 'ESTO ESCALA BIEN'],
      hurt: ['ERA UNA PRUEBA', 'BUG CONOCIDO', 'LO PARCHEO LUEGO'],
      block: ['ESCUDO TÉRMICO', 'REDUNDANCIA ACTIVA'],
      gloat: ['ESTABA EN LA HOJA DE RUTA'],
      low: ['REINICIANDO SISTEMAS', 'NECESITO MÁS FONDOS'],
      win: ['LO COMPRÉ TODO Y GANÉ'],
      vs: { trumpo: 'TU MURO NO TIENE WIFI', zuck: 'TE RETO A UNA JAULA', albertito: 'ÉL NO INVENTÓ MI COHETE' }
    },
    taunt: '¡AL ESPACIO!'
  },

  {
    id: 'pulga', name: 'EL PULGA', short: 'PULGA', real: 'EL DE LA ZURDA',
    title: 'ZURDA REGISTRADA', type: 'futbol', sub: 'TRANQUILO',
    bio: 'CAMINA, CAMINA Y DE PRONTO TE ELIMINA.',
    speed: 1.60, power: 0.85, hp: 95, jump: 1.00, reach: 0.90, atkSpeed: 1.20,
    pal: { h: '#8a6a44', H: '#5f4830', s: '#e8b98f', S: '#bc8f66', L: '#ffd9b0', b: '#6b4f30', w: '#ffffff', k: '#1a1a1a', e: '#5f4830', m: '#8c4a4a' },
    head: ['................',
           '....hhhhhhhh....',
           '..hhhhhhhhhhhh..',
           '.hhhhhhhhhhhhhh.',
           '.hHssssssssssHh.',
           '.hsssssssssssss.',
           '.sseeesseeessss.',
           '.sswkwsswkwssss.',
           '.ssssssssssssss.',
           '.sssssSSSssssss.',
           '.bbsssssssssbbb.',
           '.bbbbmmmmmbbbbb.',
           '.bbbbbbbbbbbbbb.',
           '.Sbbbbbbbbbbbb..',
           '..SSbbbbbbbbS...',
           '....ssssss......'],
    body: { style: 'stripes', main: '#7fd0e8', dark: '#3a7f96', light: '#f2f2ef', accent: '#f5c542', skin: '#e8b98f', legs: '#e8ecf5', legsDark: '#b9c4d8' },
    special: { name: 'TIRO LIBRE', cost: 30, kind: 'projectile', dmg: 11,
      speed: 2.6, homing: 0.13, art: 'balon', oy: -29, life: 170, say: 'AL ÁNGULO' },
    superMove: { name: 'GAMBETA INFINITA', cost: 100, kind: 'dash', dmg: 9, hits: 4, speed: 4.6, dur: 36,
      say: '¡SE FUE DE CUATRO!' },
    quotes: ['Y HOY TAMPOCO FUE PENAL.', 'LA PELOTA NO SE MANCHA. TU RÉCORD SÍ.',
             'ANDÁ, TRANQUILO, NO PASA NADA.'],
    barks: {
      intro: ['DALE, TRANQUILO', 'ANDÁ, VENÍ', 'JUGUEMOS Y YA'],
      hit: ['¡GOLAZO!', 'ANDÁ P’ALLÁ', 'AL ÁNGULO'],
      hurt: ['¡ESO ES FALTA!', '¡AMARILLA PARA ÉL!', 'ME PEGÓ, ÁRBITRO'],
      block: ['LA TOQUÉ, ÁRBITRO', 'NO PASA NADA'],
      gloat: ['ESTO NO SE ENSEÑA'],
      low: ['ME QUEDAN DOS MINUTOS', 'PIDO EL CAMBIO'],
      win: ['Y HOY TAMPOCO FUE PENAL'],
      vs: { siuuu: 'OTRA VEZ VOS NO', roca: 'NO ME EMPUJES ASÍ' }
    },
    taunt: 'ANDÁ P’ALLÁ'
  },

  {
    id: 'siuuu', name: 'SIUUU', short: 'SIUUU', real: 'EL DEL SALTO',
    title: 'MÁQUINA DE SALTAR', type: 'ego', sub: 'ABDOMINALES',
    bio: 'SALTA MÁS ALTO QUE TU AUTOESTIMA.',
    speed: 1.35, power: 1.05, hp: 100, jump: 1.35, reach: 1.05, atkSpeed: 1.00,
    pal: { h: '#211a14', H: '#0f0c08', s: '#e0a878', S: '#b07f54', L: '#ffc99a', w: '#ffffff', k: '#2a1a1a', e: '#0f0c08', m: '#8c3b3b' },
    head: ['................',
           '....hhhhhhhh....',
           '..hhhhhhhhhhhh..',
           '.hhhhhhhhhhhhhh.',
           '.hhhhhhhhhhhhhh.',
           '.HssssssssssssH.',
           '.sseeesseeessss.',
           '.sswkwsswkwssss.',
           '.ssssssssssssss.',
           '.ssssssSSssssss.',
           '.ssswwwwwwwsss..',
           '.ssswwwwwwwsss..',
           '.sssskkkkksss...',
           '.SsssssssssssS..',
           '..SSSSSSSSSSS...',
           '....ssssss......'],
    body: { style: 'jersey', main: '#c0392b', dark: '#8f1218', light: '#f2f2ef', accent: '#f5c542', skin: '#e0a878', legs: '#f2f2ef', legsDark: '#c9cfdd' },
    special: { name: 'CABEZAZO ORBITAL', cost: 30, kind: 'dash', dmg: 11, hits: 2, speed: 4.4, dur: 30, air: true,
      say: '¡SIGO SUBIENDO!' },
    superMove: { name: 'GRITO SIUUU', cost: 100, kind: 'projectile', dmg: 13, count: 2, spread: 0.5,
      speed: 3.0, art: 'grito', oy: -49, life: 130, big: true, effect: 'slow', say: '¡SIUUUUUU!' },
    quotes: ['SOY EL MEJOR. LO DIGO YO, QUE SÉ DE ESTO.', 'ESAS CINCO LAS GANÉ SOLO.',
             'EL TALENTO SIN TRABAJO NO ES NADA. YO TENGO LOS DOS.'],
    barks: {
      intro: ['SIUUU', 'MÍRAME BIEN', 'SOY EL MEJOR, YA ESTÁ'],
      hit: ['¡SIUUU!', 'CALIDAD Y TRABAJO', 'ESO ES TÉCNICA'],
      hurt: ['¡ERA FALTA!', '¡ME EMPUJÓ!', 'ESO NO VALE'],
      block: ['ABDOMINALES DE ACERO', 'NI ME DESPEINO'],
      gloat: ['POR ESO SOY YO'],
      low: ['ESTO NO SE ACABA', 'AÚN SOY EL MEJOR'],
      win: ['LO HICE YO SOLO'],
      vs: { pulga: 'OTRA VEZ EL DE LA ZURDA', roca: 'YO TENGO MÁS ABDOMINALES', shakira: 'YO CANTO MEJOR' }
    },
    taunt: '¡SIUUU!'
  },

  {
    id: 'ramses', name: 'CHEF RAMSÉS', short: 'RAMSÉS', real: 'EL CHEF QUE GRITA',
    title: 'TODO ESTÁ CRUDO', type: 'cocina', sub: 'GRITO',
    bio: 'NUNCA VIO UN PLATO BIEN HECHO.',
    speed: 1.25, power: 1.10, hp: 105, jump: 0.95, reach: 1.00, atkSpeed: 1.05,
    pal: { h: '#e8d9a0', H: '#c0ad72', s: '#f2c9a0', S: '#c79c74', L: '#ffe4c6', w: '#ffffff', k: '#7a2a2a', e: '#c0ad72', m: '#8c3b3b' },
    head: ['..h..h..h..h....',
           '..hh.hh.hh.hh...',
           '..hhhhhhhhhhhh..',
           '.hhhhhhhhhhhhhh.',
           '.hHssssssssssHh.',
           '.ssssssssssssss.',
           '.seeessseeesssS.',
           '.sswkwsswkwssss.',
           '.ssssssssssssss.',
           '.ssssssSSssssss.',
           '.sskkkkkkkkkss..',
           '.sskkkkkkkkkss..',
           '.sssskkkkksss...',
           '.SsssssssssssS..',
           '..SSSSSSSSSSS...',
           '....ssssss......'],
    body: { style: 'chef', main: '#f2f2ef', dark: '#c9cfdd', light: '#ffffff', accent: '#3a4560', skin: '#f2c9a0', legs: '#3a4560', legsDark: '#252b38' },
    special: { name: '¡ESTÁ CRUDO!', cost: 30, kind: 'projectile', dmg: 10, count: 2, spread: 0.35,
      speed: 3.2, art: 'plato', oy: -44, life: 120, say: '¡ESTO ESTÁ CRUDÍSIMO!' },
    superMove: { name: 'PESADILLA EN COCINA', cost: 100, kind: 'rain', dmg: 9, count: 7, art: 'sarten',
      effect: 'burn', say: '¡FUERA DE MI COCINA!' },
    quotes: ['¡ESTO ESTÁ MÁS CRUDO QUE TU DEFENSA!', 'TE DEJÉ QUEMADO POR FUERA Y TEMBLANDO POR DENTRO.',
             '¿ESTO LO HICISTE TÚ? ¿CON LAS MANOS?'],
    barks: {
      intro: ['¡ESTO ESTÁ CRUDO!', '¿QUÉ ES ESTO?', '¡SERVICIO EN CINCO!'],
      hit: ['¡FUERA DE MI COCINA!', '¡AL FUEGO!', '¡ASÍ SE HACE!'],
      hurt: ['¡ESTÁ FRÍO Y SOSO!', '¡SIN SAL Y SIN GRACIA!', '¡ESTO ES UN DESASTRE!'],
      block: ['SARTÉN ARRIBA', 'NO ENTRA NADA CRUDO'],
      gloat: ['POR FIN ALGO AL PUNTO'],
      low: ['SE ME QUEMA TODO', 'EL SERVICIO ES UN CAOS'],
      win: ['POR FIN ALGO BIEN HECHO'],
      vs: { bob: 'ESO NO SE COME', zuck: 'NINGUNA IA SABE SAZONAR', shakira: 'MENOS BAILE Y MÁS FUEGO' }
    },
    taunt: '¡ESTÁ CRUDO!'
  },

  {
    id: 'bob', name: 'BOB LA BROCHA', short: 'BOB', real: 'EL PINTOR AMABLE',
    title: 'ACCIDENTES FELICES', type: 'oleo', sub: 'ARBOLITO',
    bio: 'NO CREE EN LOS ERRORES. PEGA IGUAL.',
    speed: 1.10, power: 0.90, hp: 115, jump: 0.90, reach: 1.00, atkSpeed: 0.90,
    pal: { h: '#6b4a2a', H: '#4a331c', s: '#f2c9a0', S: '#c79c74', L: '#ffe4c6', b: '#5a3d22', w: '#ffffff', k: '#1a1a1a', e: '#4a331c', m: '#8c5b4b' },
    head: ['...hhhhhhhhhh...',
           '..hhhhhhhhhhhh..',
           '.hhhhhhhhhhhhhh.',
           'hhhhhhhhhhhhhhhh',
           'hhhhssssssssHhhh',
           'hhhsssssssssshhh',
           '.sseeesseeessss.',
           '.sswkwsswkwssss.',
           '.ssssssssssssss.',
           '.sssssSSSssssss.',
           '.bbsssssssssbbb.',
           '.bbbbmmmmmbbbbb.',
           '.bbbbbbbbbbbbbb.',
           '.Sbbbbbbbbbbbb..',
           '..SSbbbbbbbbS...',
           '....ssssss......'],
    body: { style: 'shirt', main: '#7fa8d8', dark: '#4a6f9e', light: '#e8f0fa', accent: '#f0932b', skin: '#f2c9a0' },
    special: { name: 'ARBOLITO FELIZ', cost: 30, kind: 'heal', heal: 22, guard: 200, art: 'arbol', say: 'UN AMIGUITO AQUÍ' },
    superMove: { name: 'ACCIDENTE FELIZ', cost: 100, kind: 'rain', dmg: 8, count: 8, art: 'mancha',
      effect: 'slow', say: 'NO HAY ERRORES, SOLO ACCIDENTES FELICES' },
    quotes: ['NO PERDISTE, TUVISTE UN ACCIDENTE FELIZ.', 'UN ARBOLITO AQUÍ, UN MORETÓN ALLÁ.',
             'HOY PINTAMOS UNA NUBECITA. Y TU DERROTA.'],
    barks: {
      intro: ['HOY PINTAMOS ALGO BONITO', 'RESPIRA HONDO', 'SIN PRISA, AMIGO'],
      hit: ['ACCIDENTE FELIZ', 'UN TOQUECITO AQUÍ', 'QUEDA MUY BIEN'],
      hurt: ['NO PASA NADA', 'ESO TIENE ARREGLO', 'VAYA, QUÉ TEXTURA'],
      block: ['EL LIENZO AGUANTA', 'TRANQUILO, TRANQUILO'],
      gloat: ['MIRA QUÉ ARMONÍA'],
      low: ['NECESITO MÁS BLANCO', 'CASI ACABO EL CUADRO'],
      win: ['QUEDÓ PRECIOSO'],
      vs: { ramses: 'GRITAR NO PINTA NADA', trumpo: 'TE PINTO UNA PUERTA' }
    },
    taunt: 'TODO TIENE ARREGLO'
  },

  {
    id: 'roca', name: 'LA ROCA', short: 'LA ROCA', real: 'EL DE LA CEJA',
    title: '¿HUELES ESO?', type: 'roca', sub: 'CEJA',
    bio: 'DESAYUNA MÁS QUE TÚ EN UNA SEMANA.',
    speed: 0.95, power: 1.35, hp: 130, jump: 0.80, reach: 1.15, atkSpeed: 0.85,
    pal: { s: '#b0774a', S: '#8a5a34', L: '#c98f5e', w: '#ffffff', k: '#1a1a1a', e: '#3a2418', m: '#7a3b3b' },
    head: ['................',
           '.....ssssss.....',
           '...ssssssssss...',
           '..LLLLLLLLLLLL..',
           '.LLLLLLLLLLLLLL.',
           '.sssssssseeesss.',
           '.seeessssssssss.',
           '.sswkwsswkwssss.',
           '.ssssssssssssss.',
           '.ssssssSSssssss.',
           '.sssssSSSSsssss.',
           '.sssmmmmmmssss..',
           '.ssssssssssssss.',
           '.SsssssssssssS..',
           '..SSSSSSSSSSS...',
           '....ssssss......'],
    body: { style: 'tee', main: '#2e3240', dark: '#1b1e28', light: '#b0774a', accent: '#c9a06d', skin: '#b0774a', bulk: true, legs: '#5f5740', legsDark: '#413c2c' },
    special: { name: 'CEJA LEVANTADA', cost: 30, kind: 'projectile', dmg: 8,
      speed: 2.2, art: 'ceja', oy: -49, life: 120, effect: 'slow', say: '¿HUELES LO QUE ESTOY COCINANDO?' },
    superMove: { name: 'CODAZO DEL PUEBLO', cost: 100, kind: 'dash', dmg: 14, hits: 2, speed: 4.0, dur: 32,
      say: '¡ESTO VA POR EL PUEBLO!' },
    quotes: ['¿SABES LO QUE ESTABA COCINANDO? ESTO.', 'LEVANTÉ UNA CEJA Y TE CAÍSTE SOLO.',
             'NO ERES DEMASIADO PEQUEÑO. SOY YO, QUE SOY ENORME.'],
    barks: {
      intro: ['¿HUELES ESO?', 'MÍRAME A LA CEJA', 'VAMOS A TRABAJAR'],
      hit: ['¡ESTO VA POR EL PUEBLO!', '¿SABES QUÉ COCINABA?', '¡ARRIBA!'],
      hurt: ['ESO NI SE SIENTE', 'SIGUE INTENTÁNDOLO', 'ERA UN MASAJE'],
      block: ['PARED DE MÚSCULO', 'NI ME MUEVO'],
      gloat: ['DEMASIADO FÁCIL'],
      low: ['AHORA ME ENFADO', 'SE ACABÓ EL CALENTAMIENTO'],
      win: ['FIN DEL SERVICIO'],
      vs: { zuck: '¿ESO ES UN HUMANO?', pulga: 'NO TE ME ESCAPES', shakira: '¿ESO ES BAILE O QUÉ?' }
    },
    taunt: '¿HUELES ESO?'
  },

  {
    id: 'zuck', name: 'ZUCK-BOT', short: 'ZUCK', real: 'EL DE LA RED',
    title: 'HUMANO VERIFICADO', type: 'algoritmo', sub: 'CAPTCHA',
    bio: 'JURA QUE ES UNA PERSONA NORMAL.',
    speed: 1.20, power: 0.95, hp: 95, jump: 1.00, reach: 0.95, atkSpeed: 1.00,
    pal: { h: '#8a6a44', H: '#5f4830', s: '#f0e4dc', S: '#c9bdb4', L: '#fff6f0', c: '#48e0d0', w: '#ffffff', k: '#3a4560', e: '#5f4830', m: '#8c6b6b' },
    head: ['................',
           '...hhhhhhhhhh...',
           '..hhhhhhhhhhhh..',
           '.hhhhhhhhhhhhhh.',
           '.hhhhhhhhhhhhhh.',
           '.hssssssssssssh.',
           '.sssssssssssss..',
           '.sscwcsscwcssss.',
           '.ssssssssssssss.',
           '.ssssssSSssssss.',
           '.ssssssssssssss.',
           '.ssskkkkkkksss..',
           '.ssssssssssssss.',
           '.SsssssssssssS..',
           '..SSSSSSSSSSS...',
           '....ssssss......'],
    body: { style: 'tee', main: '#6a7590', dark: '#414c66', light: '#f0e4dc', accent: '#48e0d0', skin: '#f0e4dc', legs: '#39415e', legsDark: '#252b42' },
    special: { name: '¿ERES UN ROBOT?', cost: 30, kind: 'projectile', dmg: 9, count: 2, spread: 0.3,
      speed: 3.4, art: 'captcha', oy: -44, life: 120, effect: 'slow', say: 'SELECCIONA TODOS LOS SEMÁFOROS' },
    superMove: { name: 'TÉRMINOS NUEVOS', cost: 100, kind: 'rain', dmg: 9, count: 8, art: 'doc',
      say: 'ACEPTAR O ACEPTAR' },
    quotes: ['HE ACEPTADO LOS TÉRMINOS DE TU DERROTA.', 'TU PARTIDA SE GUARDÓ. Y SE VENDIÓ.',
             'ESTO ES LO QUE UN HUMANO NORMAL DIRÍA AHORA.'],
    barks: {
      intro: ['HOLA. SOY HUMANO.', 'INICIANDO COMBATE', 'ME ALEGRA VERTE. ES CIERTO.'],
      hit: ['DATO REGISTRADO', 'ME GUSTA ESTO', 'INTERACCIÓN POSITIVA'],
      hurt: ['ERROR INESPERADO', 'REPORTANDO INCIDENCIA', 'ESO NO ESTABA EN EL PLAN'],
      block: ['FIREWALL ACTIVO', 'SOLICITUD DENEGADA'],
      gloat: ['EL ALGORITMO TE CONOCE'],
      low: ['MODO DE EMERGENCIA', 'GUARDANDO PARTIDA'],
      win: ['ACEPTASTE LOS TÉRMINOS'],
      vs: { roca: 'MÚSCULO NO ES UN DATO', trumpo: 'YA TENGO TUS DATOS', musko: 'COPIÉ TU FUNCIÓN', albertito: 'TU FÓRMULA ES OPEN SOURCE' }
    },
    taunt: 'ESTOY OPTIMIZANDO'
  },

  {
    id: 'shakira', name: 'LA LOBA', short: 'LOBA', real: 'LA DE LAS CADERAS',
    title: 'LAS CADERAS NO MIENTEN', type: 'ritmo', sub: 'ESCENARIO',
    bio: 'TE DESARMA BAILANDO Y ENCIMA TE LO CANTA.',
    speed: 1.30, power: 1.00, hp: 100, jump: 1.10, reach: 0.95, atkSpeed: 1.10,
    pal: { h: '#e8c060', H: '#b8913a', s: '#e8b585', S: '#c08f60', L: '#ffd7a8', w: '#ffffff', k: '#1a1a1a', e: '#8a6a30', m: '#c05070' },
    head: ['................',
           '...hhhhhhhhhh...',
           '..hhhhhhhhhhhh..',
           '.hhhhhhhhhhhhhh.',
           '.hhsssssssssshh.',
           '.hssssssssssssh.',
           '.hseeesseeesshh.',
           '.hswkwsswkwsshh.',
           '.hssssssssssshh.',
           '.hsssssSSsssshh.',
           '.hssssmmmmsshhh.',
           '.hhsssssssshhhh.',
           '.hhhSSSSSShhhhh.',
           'hhhhSSSShhhhhhh.',
           'hhh.ssssss.hhhh.',
           'hh..ssssss..hhh.'],
    body: { style: 'stage', main: '#d8447a', dark: '#9c2a54', light: '#ffd166', accent: '#f0e0a0', skin: '#e8b585', legs: '#3a2a4a', legsDark: '#241a30' },
    special: { name: 'CADERAZO', cost: 30, kind: 'projectile', dmg: 12,
      speed: 1.7, art: 'onda', oy: -46, life: 46, push: 5, say: 'LAS CADERAS NO MIENTEN' },
    superMove: { name: 'AULLIDO', cost: 100, kind: 'projectile', dmg: 14, count: 2, spread: 0.45,
      speed: 2.6, art: 'aullido', oy: -60, life: 120, big: true, effect: 'stun', say: '¡AUUUUU!' },
    barks: {
      intro: ['¿BAILAMOS O PELEAMOS?', 'ESTO ES UN ESPECTÁCULO', 'SUERTE, LA VAS A NECESITAR'],
      hit: ['¡ESO SE SIENTE!', 'UN, DOS, TRES', 'AL RITMO, CARIÑO'],
      hurt: ['¡ME PISASTE!', 'ESO NO ESTABA ENSAYADO', 'FUERA DE COMPÁS'],
      block: ['NI ME DESPEINO', 'ESO NO ENTRA EN EL SHOW'],
      gloat: ['LAS CADERAS NUNCA MIENTEN'],
      low: ['ÚLTIMA CANCIÓN', 'ME QUEDA UN BIS'],
      win: ['GRACIAS, BUENAS NOCHES'],
      vs: { trumpo: 'TU MURO NO TIENE RITMO', albertito: 'ESTO NO SE CALCULA', siuuu: 'MENOS GRITO Y MÁS BAILE' }
    },
    quotes: ['LAS CADERAS NO MIENTEN. TÚ SÍ.', 'TE GANÉ Y ADEMÁS TE PUSE MÚSICA.',
             'GRACIAS, BUENAS NOCHES, HE SIDO YO.'],
    taunt: '¿ASÍ BAILAS?'
  },

  {
    id: 'albertito', name: 'ALBERTITO', short: 'ALBERT', real: 'EL DEL PELO',
    title: 'TODO ES RELATIVO', type: 'ciencia', sub: 'PIZARRA',
    bio: 'PEGA POCO PERO YA CALCULÓ DÓNDE VAS A ESTAR.',
    speed: 1.00, power: 0.85, hp: 85, jump: 0.85, reach: 0.85, atkSpeed: 0.95,
    pal: { h: '#e8e8ee', H: '#b8b8c4', g: '#d8d8e0', s: '#f0d0b0', S: '#c9a883', L: '#fff0dc', w: '#ffffff', k: '#1a1a1a', e: '#c8c8d0', m: '#a8555a' },
    head: ['.h.h.hhhh.h.h...',
           '.hhhhhhhhhhhhh..',
           'hhhhhhhhhhhhhhh.',
           'hhh.ssssssss.hhh',
           'hh.ssssssssss.hh',
           '.sssssssssssss..',
           '.seeessseeessss.',
           '.sswkwsswkwssss.',
           '.ssssssssssssss.',
           '.sssssSSSssssss.',
           '.sgggggggggggs..',
           '.sgggggggggggs..',
           '.sssmmmmmmsss...',
           '.SsssssssssssS..',
           '..SSSSSSSSSSS...',
           '....ssssss......'],
    body: { style: 'labcoat', main: '#e8e4dc', dark: '#b8b2a6', light: '#ffffff', accent: '#5a6478', skin: '#f0d0b0', legs: '#4a4740', legsDark: '#2e2c28', short: true },
    special: { name: 'E = M C 2', cost: 30, kind: 'projectile', dmg: 7,
      speed: 2.0, art: 'formula', oy: -49, life: 170, grow: true, say: 'ES SENCILLO, MIRA' },
    superMove: { name: 'AGUJERO NEGRO', cost: 100, kind: 'vortex', dmg: 4, say: 'ESTO SE VA A PONER DENSO' },
    barks: {
      intro: ['TODO ES RELATIVO', 'YA CALCULÉ ESTO', 'LA IMAGINACIÓN ES MÁS ÚTIL'],
      hit: ['LA FÓRMULA FUNCIONA', 'ERA PREVISIBLE', 'MASA POR VELOCIDAD'],
      hurt: ['DATO INESPERADO', 'HAY QUE REVISAR EL MODELO', 'ERROR EXPERIMENTAL'],
      block: ['CAMPO DE FUERZA', 'ESO YA LO PREVÍ'],
      gloat: ['LA CIENCIA GANA SIEMPRE'],
      low: ['NECESITO MÁS DATOS', 'REVISANDO HIPÓTESIS'],
      win: ['LO PUBLICARÉ MAÑANA'],
      vs: { musko: 'ESE COHETE ES MÍO', zuck: 'TU IA ME COPIÓ', roca: 'LA FÍSICA TIENE LÍMITES' }
    },
    quotes: ['TODO ES RELATIVO. TU DERROTA NO.', 'LA LOCURA ES REPETIR ESTO ESPERANDO GANAR.',
             'NO ERA SUERTE, ERA GEOMETRÍA.'],
    taunt: 'FASCINANTE'
  }
];

const byId = id => ROSTER.find(c => c.id === id);
